
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS cargo TEXT,
  ADD COLUMN IF NOT EXISTS empresa TEXT,
  ADD COLUMN IF NOT EXISTS endereco TEXT,
  ADD COLUMN IF NOT EXISTS numero TEXT,
  ADD COLUMN IF NOT EXISTS complemento TEXT,
  ADD COLUMN IF NOT EXISTS bairro TEXT,
  ADD COLUMN IF NOT EXISTS cidade TEXT,
  ADD COLUMN IF NOT EXISTS uf TEXT,
  ADD COLUMN IF NOT EXISTS cep TEXT,
  ADD COLUMN IF NOT EXISTS renda_familiar TEXT,
  ADD COLUMN IF NOT EXISTS trabalha BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS profissao TEXT,
  ADD COLUMN IF NOT EXISTS faixa_valor_imovel TEXT,
  ADD COLUMN IF NOT EXISTS finalidade_compra TEXT,
  ADD COLUMN IF NOT EXISTS procura_financiamento BOOLEAN DEFAULT false;
