-- Seed missing notification templates referenced by the app and Edge Functions.
-- Existing templates are not overwritten so Super Admin customizations stay intact.

insert into public.notification_templates
  (name, slug, category, event_key, channel, channels, title, message, variables, is_active, editable_by_admin, dedupe_window_seconds, subject, html_body)
values
  (
    'Comunicado do sistema',
    'system_announcement',
    'system',
    'system_announcement',
    'system',
    array['system', 'push']::text[],
    'Comunicado',
    '{title}' || E'\n\n' || '{message}',
    array['title', 'message']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'Lembrete para atualizar telefone',
    'update_phone_reminder',
    'account',
    'update_phone_reminder',
    'system',
    array['system']::text[],
    'Atualize seu telefone',
    'Atualize seu telefone/WhatsApp para continuar recebendo notificações importantes.',
    array[]::text[],
    true,
    true,
    86400,
    null,
    null
  ),
  (
    'Lead retornou',
    'lead_reentry',
    'lead',
    'lead_reentry',
    'system',
    array['system', 'push']::text[],
    'Lead retornou',
    'O lead {lead_name} retornou ao atendimento.',
    array['lead_name']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'Lead movido',
    'lead_moved_system',
    'lead',
    'lead_moved_system',
    'system',
    array['system']::text[],
    'Lead movido',
    '{lead_name} foi movido de "{from_stage}" para "{to_stage}".',
    array['lead_name', 'from_stage', 'to_stage']::text[],
    true,
    true,
    120,
    null,
    null
  ),
  (
    'WhatsApp desconectado (compatibilidade)',
    'whatsapp_disconnected_system',
    'whatsapp',
    'whatsapp_disconnected_system',
    'system',
    array['system', 'push']::text[],
    'WhatsApp desconectado',
    'A sessão "{session_name}" do WhatsApp foi desconectada. Reconecte o QR Code para evitar falhas no atendimento e nas automações.',
    array['session_name', 'display_name']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'WhatsApp desconectado para administrador',
    'whatsapp_disconnected_admin',
    'whatsapp',
    'whatsapp_disconnected_admin',
    'system',
    array['system', 'push']::text[],
    'WhatsApp desconectado',
    'A sessão "{session_name}" do WhatsApp foi desconectada na organização. Verifique a conexão para evitar falhas operacionais.',
    array['session_name']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'SLA próximo do limite',
    'sla_warning',
    'sla',
    'sla_warning',
    'system',
    array['system', 'push']::text[],
    'SLA próximo do limite',
    'O lead {lead_name} está aguardando atendimento há {minutes} minutos.',
    array['lead_name', 'minutes']::text[],
    true,
    true,
    3600,
    null,
    null
  ),
  (
    'SLA vencido',
    'sla_overdue',
    'sla',
    'sla_overdue',
    'system',
    array['system', 'push']::text[],
    'SLA vencido',
    'O lead {lead_name} ultrapassou o SLA e está aguardando há {minutes} minutos.',
    array['lead_name', 'minutes']::text[],
    true,
    true,
    3600,
    null,
    null
  ),
  (
    'SLA vencido para gestor',
    'sla_overdue_manager',
    'sla',
    'sla_overdue_manager',
    'system',
    array['system', 'push']::text[],
    'SLA vencido',
    'O lead {lead_name} ultrapassou o SLA e está aguardando há {minutes} minutos. Verifique com a equipe responsável.',
    array['lead_name', 'minutes']::text[],
    true,
    true,
    3600,
    null,
    null
  ),
  (
    'Automação iniciada',
    'automation_started',
    'automation',
    'automation_started',
    'system',
    array['system']::text[],
    'Automação iniciada',
    'A automação "{nome_automacao}" foi iniciada para o lead {nome_lead}.',
    array['nome_automacao', 'nome_lead']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'Falha em automação',
    'automation_failed',
    'automation',
    'automation_failed',
    'system',
    array['system', 'push']::text[],
    'Falha em automação',
    'A automação "{nome_automacao}" falhou para o lead {nome_lead}. Motivo: {erro}.',
    array['nome_automacao', 'nome_lead', 'erro']::text[],
    true,
    true,
    300,
    null,
    null
  ),
  (
    'Falhas recorrentes em automação',
    'automation_repeated_failures',
    'automation',
    'automation_repeated_failures',
    'system',
    array['system', 'push']::text[],
    'Automação com falhas recorrentes',
    'A automação "{nome_automacao}" falhou {total_falhas} vezes. Revise a configuração para evitar perda de atendimento.',
    array['nome_automacao', 'total_falhas']::text[],
    true,
    true,
    1800,
    null,
    null
  ),
  (
    'Atualização de gamificação',
    'gamification_update',
    'gamification',
    'gamification_update',
    'email',
    array['email']::text[],
    'Atualização de gamificação',
    '{title}' || E'\n\n' || '{message}',
    array['user_name', 'title', 'message']::text[],
    true,
    true,
    300,
    '{title}',
    '<p>Olá, {user_name}.</p><p>{message}</p>'
  ),
  (
    'Teste de push',
    'test_push',
    'system',
    'test_push',
    'push',
    array['push']::text[],
    'Teste de notificação',
    'Se você recebeu esta notificação, o push está funcionando neste dispositivo.',
    array[]::text[],
    true,
    true,
    10,
    null,
    null
  )
on conflict (slug) do nothing;
