ALTER TABLE meta_campaign_insights 
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS budget NUMERIC,
ADD COLUMN IF NOT EXISTS budget_type TEXT,
ADD COLUMN IF NOT EXISTS conversations_count INTEGER DEFAULT 0;
